### ISSUE TITLE
define shell functions

### ISSUE THREAD

**Issue by nrdxp** [numtide/devshell#106]
Perhaps this is already possible and I'm not using my imagination, but I'm a zsh user and I'd like to set an alias for nix to include `experimental-featues` in the devshell. Since having shell agnostic aliases may be kind of a pain to implement, it seems like simple shell functions should suffice as a more friendly approach to accomplish the same purpose. 

I tried making a minimal module and setting `config.devshell.startup.nix.text = "function nix () #..."`, but it looks like it didn't make it to the final shell.

**Comment by zimbatm** [comment]
devshell itself only supports bash at the moment, because `nix-shell` and `nix develop` mandate bash. I assume that you are using direnv, where direnv loads the .envrc in a bash sub-shell, and then re-exports the environment variables to the host shell.

I think most functions and aliases are taken care of by the `[[commands]]` like this:
```toml
[[commands]]
name = "nix-exp"
command = "nix --experimental-feature flakes \"$@\""
```
This adds a new `nix-exp` binary in the PATH.

For Nix specifically, another option is to tell Nix to load the config from a specific location in the repo using NIX_USER_CONF_FILES (only works in Nix 2.4+). Eg:

```toml
[[env]]
name = "NIX_USER_CONF_FILES"
eval = "$PWD/nix.conf"
```

or inline the config in the env directly:
```toml
[[env]]
name = "NIX_CONFIG"
value = """
experimental-features = nix-command flake
"""
```
