### ISSUE TITLE
Additional binaries of a package cannot be displayed in `menu`

### ISSUE THREAD

**Issue by Austreelis** [numtide/devshell#131]
I'm introducing nix into a rust project using rustup (for now at least). At first we'd like to keep both the option of building using rustup-installed toolchains and with nix. We're using devshell to get a nice shell and easy setup for people still getting into rust. I'd like to specify commands for the rust tools brought in by rustup (cargo, rustfmt, ...), but since those binaries are already brought in by rustup, adding a command creates a conflict:

```
error: builder for '/nix/store/lyf1pzj3zl6qp8mp42dr0h090zp0x6ln-devshell-dir.drv' failed with exit code 25;
       last 1 log lines:
       > collision between `/nix/store/5wcfjp9pv32fjji2hf7f2nyga19dq0j4-rustup-1.23.1/bin/cargo' and `/nix/store/rgr3da2h1jzjb07sxwmjclk9vmqk2n1k-cargo/bin/cargo'
       For full logs, run 'nix log /nix/store/lyf1pzj3zl6qp8mp42dr0h090zp0x6ln-devshell-dir.drv'.
error: 1 dependencies of derivation '/nix/store/925qnsswhyrn1fddssi784bncmrx9dxv-project-entrypoint.drv' failed to build
error: 1 dependencies of derivation '/nix/store/bxchzixk3bnxjv365s9ass7pi0x4ncbp-project-env.drv' failed to build
```

sample `devshell.toml`:

```toml
[[commands]]
package = "rustup"

[[commands]]
name = "cargo"
command = "$DEVSHELL_DIR/bin/cargo" 
```

N.B.: The cargo binary *exists* under `$DEVSHELL_DIR/bin`, removing the last command above works well and we can use `cargo` or others in the devshell. The problem is we can't have a menu entry for it, so this is *mostly* a cosmetic issue.

Expected `menu` output (missing a bunch of programs but you hopefully get the idea):

```
[formatters]

  rustfmt  - A tool for formatting Rust code according to style guidelines

[general commands]

     menu  - prints this menu

[tools]

    cargo  - Downloads your Rust project's dependencies and builds your project
   rustup  - The Rust toolchain installer
```

**Proposed solution**

I'd like to be able to specify extra "package-or-command-less" commands to a command, say something like that:

```toml
[[commands]]
package = "rustup"
category = "tools"

[[commands.extra]]
name = "rustfmt"
help = "A tool for formatting Rust code according to style guidelines"

[[commands.extra]]
name = "cargo"
help = "Downloads your Rust project's dependencies and builds your project"
```

(Or if some are not familiar with TOML's nested arrays of tables declarations, just to be clear for everyone:)

```toml
[[commands]]
package = "rustup"
category = "tools"
extra = [
  { name = "rustfmt", help = "A tool for formatting Rust code according to style guidelines" },
  { name = "cargo", help = "Downloads your Rust project's dependencies and builds your project" },
]
```

This is rather simple to implement and I'll soon be able to open a PR (EDIT: #132 ).

Other solutions I considered were:
- Allowing to manually declare menu entries, e.g. like
    ```toml
    [[menu]]
    name = "cargo"
    category = "tools"
    ```
    But it allows to arbitrarily add menu entries not related to a command (unless we add a way to specify the package the command depends on, but I'd rather have that in the commands config. Just my opinion though), which bothers me a bit. But it's more general than our particular usecase, even though I don't know if that's really useful.
- Using another name:
    ```toml
    [[commands]]
    name = "cargo-cmd"
    command = "cargo"
    ```
  But I think this is impractical even with autocompletion, because that's really just to have it in the help menu and it cannot have the actual name of the program.
- Manually append menu entries in rustup command's `help` attribute (works, for now, but that's really hacky).

**Comment by blaggacao** [comment]
I thought about about it and I agree with the `extra` notation.

Another alternative, which does _not_ allow to set individual help text, so not an option:

```toml
[[commands]]
package = "rustup"
category = "tools" 
names = [ ]
```

**Comment by zimbatm** [comment]
What's wrong with a bit of repetition?

```toml
[[commands]]
package = "rustup"
category = "tools"

[[commands]]
name = "rustfmt"
help = "A tool for formatting Rust code according to style guidelines"
package = "rustup"

[[commands]]
name = "cargo"
help = "Downloads your Rust project's dependencies and builds your project"
package = "rustup"
```
