### ISSUE TITLE
external script support for commands

### ISSUE THREAD

**Issue by justinabrahms** [numtide/devshell#281]
**Is your feature request related to a problem? Please describe.**

I'd like syntax highlighting for bash scripts and similar, which I don't get in TOML. 

Also, I'd like it if the scripts were invokable by people who don't want to use nix, provided they have a properly configured environment.

**Describe the solution you'd like**

instead of `command = '''...'''`, I'd like `commandFile = './scripts/foo.sh'`

**Describe alternatives you've considered**

perhaps some toml import synatx something or other, but that seems too complex.

**Additional context**

**Comment by deemp** [comment]
IDK what's you use case. Please, describe it in more details.

Currently, you can create a script file:

```sh
cat > hello.sh <<EOF
printf "hello!\n"
EOF
chmod +x hello.sh
```

Then, in `devshell.toml` (this repo uses this file for the default devshell), create a command that runs that file:

```toml
# ...
[devshell]
# ...
[[commands]]
help = "prints hello"
name = "hello"
command = "$PRJ_ROOT/hello.sh"
# ...
```

Now, you can run

```sh
$ hello
hello!
```
