### ISSUE TITLE
Use meta.description and pname where possible

### ISSUE THREAD

**Issue by blaggacao** [numtide/devshell#57]
```toml
[[commands]]
package = "git"
```

could internally fall back to

```nix
{
   name = git.pname;
   help = git.meta.description;
}
```
