### ISSUE TITLE
Add a [nixpkgs] module

### ISSUE THREAD

**Issue by zimbatm** [numtide/devshell#68]
NixOS allows the user to override nixpkgs from within the module system. What happens under the hood is quite magic really.

In order to minimize the amount of nix plumbing needed, we could introduce something like that that allows a poor-man's nixpkgs pinning and configuration:

```toml
[nixpkgs.src]
url = "git+https://github.com/NixOS/nixpkgs"
rev = "<commit-id>"
[nixpkgs.config]
allowBroken = true
allowUnfree = true
```
